name: Deploy
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
  - cron: '30 0 * * *'
jobs:
  deploy:
    name: "Deploy website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - name: install
      run: |
        make install
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make build
    - name: Deploy
      if: ${{ !github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dist
        git init -b pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m 'deploy'
        git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git pages:gh-pages